openapi: 3.0.0
info:
  title: ReChunk API
  description: Render remote components with React Native
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: localhost server for development
paths:
  "/":
    get:
      summary: Returns a JSON message.
  "/chunk/{chunkId}":
    get:
      summary: Returns a chunk by ID.
      parameters:
        - name: chunkId
          in: path
          required: true
          description: Chunk identifier.
          schema:
            type : string
            minimum: 1
      security:
        - basicAuth: []
  "/chunk/{chunkId}":
    post:
      summary: Creates a chunk by ID.
      security:
        - basicAuth: []
  "/chunk/{chunkId}":
    delete:
      summary: Deletes a chunk by ID.
      security:
        - basicAuth: []
  "/project":
    get:
      summary: Returns a project.
      security:
        - basicAuth: []
  "/project":
    post:
      summary: Creates a project.
      responses:
        '200':
          description: Successful response with API configuration.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiConfiguration'
      security:
        - basicAuth: []
components:
  schemas:
    ApiConfiguration:
      type: object
      properties:
        $schema:
          type: string
          description: URL to the JSON schema defining this object.
        entry:
          type: object
          description: Entry object (empty in this example).
        external:
          type: array
          items:
            type: string
          description: List of external references (empty in this example).
        project:
          type: string
          description: Project name associated with the API.
        publicKey:
          type: string
          description: Public key for API authentication (omitted for security).
        readKey:
          type: string
          description: Read key for accessing API data (omitted for security).
        writeKey:
          type: string
          description: Write key for modifying API data (omitted for security).
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
