/* tslint:disable */
/* eslint-disable */
/**
 * ReChunk API
 * API for managing chunks in the ReChunk project. Enables secure storage and retrieval of data chunks with project-based organization.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {mapValues} from '../runtime';
/**
 *
 * @export
 * @interface ChunkCreate
 */
export interface ChunkCreate {
  /**
   * The chunk content
   * @type {string}
   * @memberof ChunkCreate
   */
  data: string;
}

/**
 * Check if a given object implements the ChunkCreate interface.
 */
export function instanceOfChunkCreate(value: object): value is ChunkCreate {
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ChunkCreateFromJSON(json: any): ChunkCreate {
  return ChunkCreateFromJSONTyped(json, false);
}

export function ChunkCreateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChunkCreate {
  if (json == null) {
    return json;
  }
  return {
    data: json['data'],
  };
}

export function ChunkCreateToJSON(value?: ChunkCreate | null): any {
  if (value == null) {
    return value;
  }
  return {
    data: value['data'],
  };
}
