/* tslint:disable */
/* eslint-disable */
/**
 * ReChunk API
 * API for managing chunks in the ReChunk project.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {mapValues} from '../runtime';
/**
 *
 * @export
 * @interface Chunk
 */
export interface Chunk {
  /**
   *
   * @type {string}
   * @memberof Chunk
   */
  data?: string;
  /**
   *
   * @type {string}
   * @memberof Chunk
   */
  token?: string;
}

/**
 * Check if a given object implements the Chunk interface.
 */
export function instanceOfChunk(value: object): value is Chunk {
  return true;
}

export function ChunkFromJSON(json: any): Chunk {
  return ChunkFromJSONTyped(json, false);
}

export function ChunkFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Chunk {
  if (json == null) {
    return json;
  }
  return {
    data: json['data'] == null ? undefined : json['data'],
    token: json['token'] == null ? undefined : json['token'],
  };
}

export function ChunkToJSON(value?: Chunk | null): any {
  if (value == null) {
    return value;
  }
  return {
    data: value['data'],
    token: value['token'],
  };
}
