/* tslint:disable */
/* eslint-disable */
/**
 * ReChunk API
 * API for managing chunks in the ReChunk project.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {mapValues} from '../runtime';
/**
 *
 * @export
 * @interface CreateChunkForProject200Response
 */
export interface CreateChunkForProject200Response {
  /**
   *
   * @type {string}
   * @memberof CreateChunkForProject200Response
   */
  message?: string;
}

/**
 * Check if a given object implements the CreateChunkForProject200Response interface.
 */
export function instanceOfCreateChunkForProject200Response(
  value: object,
): value is CreateChunkForProject200Response {
  return true;
}

export function CreateChunkForProject200ResponseFromJSON(
  json: any,
): CreateChunkForProject200Response {
  return CreateChunkForProject200ResponseFromJSONTyped(json, false);
}

export function CreateChunkForProject200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateChunkForProject200Response {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function CreateChunkForProject200ResponseToJSON(
  value?: CreateChunkForProject200Response | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    message: value['message'],
  };
}
