/* tslint:disable */
/* eslint-disable */
/**
 * ReChunk API
 * API for managing chunks in the ReChunk project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectsProjectIdChunksChunkIdPost200Response
 */
export interface ProjectsProjectIdChunksChunkIdPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ProjectsProjectIdChunksChunkIdPost200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ProjectsProjectIdChunksChunkIdPost200Response interface.
 */
export function instanceOfProjectsProjectIdChunksChunkIdPost200Response(value: object): value is ProjectsProjectIdChunksChunkIdPost200Response {
    return true;
}

export function ProjectsProjectIdChunksChunkIdPost200ResponseFromJSON(json: any): ProjectsProjectIdChunksChunkIdPost200Response {
    return ProjectsProjectIdChunksChunkIdPost200ResponseFromJSONTyped(json, false);
}

export function ProjectsProjectIdChunksChunkIdPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectsProjectIdChunksChunkIdPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ProjectsProjectIdChunksChunkIdPost200ResponseToJSON(value?: ProjectsProjectIdChunksChunkIdPost200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

