/* tslint:disable */
/* eslint-disable */
/**
 * ReChunk API
 * API for managing chunks in the ReChunk project. Enables secure storage and retrieval of data chunks with project-based organization.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {mapValues} from '../runtime';
/**
 *
 * @export
 * @interface Token
 */
export interface Token {
  /**
   * Unique identifier for the token
   * @type {string}
   * @memberof Token
   */
  id?: string;
  /**
   * Timestamp of project creation
   * @type {Date}
   * @memberof Token
   */
  createdAt?: Date;
  /**
   * The unique identifier for the project
   * @type {string}
   * @memberof Token
   */
  projectId?: string;
  /**
   * JWT token for authentication
   * @type {string}
   * @memberof Token
   */
  token?: string;
}

/**
 * Check if a given object implements the Token interface.
 */
export function instanceOfToken(value: object): value is Token {
  return true;
}

export function TokenFromJSON(json: any): Token {
  return TokenFromJSONTyped(json, false);
}

export function TokenFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Token {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    createdAt:
      json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    projectId: json['projectId'] == null ? undefined : json['projectId'],
    token: json['token'] == null ? undefined : json['token'],
  };
}

export function TokenToJSON(value?: Token | null): any {
  if (value == null) {
    return value;
  }
  return {
    id: value['id'],
    createdAt:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    projectId: value['projectId'],
    token: value['token'],
  };
}
