#!/bin/env node

const fs = require('fs');

fs.copyFileSync(
  path.resolve(workingPath, 'package.json.bak'),
  path.resolve(workingPath, 'package.json'),
);

fs.unlinkSync(path.resolve(workingPath, 'package.json.bak'));
