/* tslint:disable */
/* eslint-disable */
/**
 * ReChunk API
 * API for managing chunks in the ReChunk project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Chunk,
  Project,
  ProjectsProjectIdChunksChunkIdPost200Response,
} from '../models/index';
import {
    ChunkFromJSON,
    ChunkToJSON,
    ProjectFromJSON,
    ProjectToJSON,
    ProjectsProjectIdChunksChunkIdPost200ResponseFromJSON,
    ProjectsProjectIdChunksChunkIdPost200ResponseToJSON,
} from '../models/index';

export interface ProjectsProjectIdChunksChunkIdDeleteRequest {
    projectId: string;
    chunkId: string;
}

export interface ProjectsProjectIdChunksChunkIdGetRequest {
    projectId: string;
    chunkId: string;
}

export interface ProjectsProjectIdChunksChunkIdPostRequest {
    projectId: string;
    chunkId: string;
    body: string;
}

export interface ProjectsProjectIdChunksGetRequest {
    projectId: string;
}

export interface ProjectsProjectIdGetRequest {
    projectId: string;
}

export interface ProjectsProjectIdPostRequest {
    projectId: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Delete a chunk from the project.
     */
    async projectsProjectIdChunksChunkIdDeleteRaw(requestParameters: ProjectsProjectIdChunksChunkIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectsProjectIdChunksChunkIdPost200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdChunksChunkIdDelete().'
            );
        }

        if (requestParameters['chunkId'] == null) {
            throw new runtime.RequiredError(
                'chunkId',
                'Required parameter "chunkId" was null or undefined when calling projectsProjectIdChunksChunkIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/projects/{projectId}/chunks/{chunkId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"chunkId"}}`, encodeURIComponent(String(requestParameters['chunkId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectsProjectIdChunksChunkIdPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete a chunk from the project.
     */
    async projectsProjectIdChunksChunkIdDelete(requestParameters: ProjectsProjectIdChunksChunkIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectsProjectIdChunksChunkIdPost200Response> {
        const response = await this.projectsProjectIdChunksChunkIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get details of a chunk in the project.
     */
    async projectsProjectIdChunksChunkIdGetRaw(requestParameters: ProjectsProjectIdChunksChunkIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Chunk>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdChunksChunkIdGet().'
            );
        }

        if (requestParameters['chunkId'] == null) {
            throw new runtime.RequiredError(
                'chunkId',
                'Required parameter "chunkId" was null or undefined when calling projectsProjectIdChunksChunkIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/projects/{projectId}/chunks/{chunkId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"chunkId"}}`, encodeURIComponent(String(requestParameters['chunkId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChunkFromJSON(jsonValue));
    }

    /**
     * Get details of a chunk in the project.
     */
    async projectsProjectIdChunksChunkIdGet(requestParameters: ProjectsProjectIdChunksChunkIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Chunk> {
        const response = await this.projectsProjectIdChunksChunkIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a chunk in the project.
     */
    async projectsProjectIdChunksChunkIdPostRaw(requestParameters: ProjectsProjectIdChunksChunkIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectsProjectIdChunksChunkIdPost200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdChunksChunkIdPost().'
            );
        }

        if (requestParameters['chunkId'] == null) {
            throw new runtime.RequiredError(
                'chunkId',
                'Required parameter "chunkId" was null or undefined when calling projectsProjectIdChunksChunkIdPost().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling projectsProjectIdChunksChunkIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/projects/{projectId}/chunks/{chunkId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"chunkId"}}`, encodeURIComponent(String(requestParameters['chunkId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectsProjectIdChunksChunkIdPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a chunk in the project.
     */
    async projectsProjectIdChunksChunkIdPost(requestParameters: ProjectsProjectIdChunksChunkIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectsProjectIdChunksChunkIdPost200Response> {
        const response = await this.projectsProjectIdChunksChunkIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get details of all chunks in the project.
     */
    async projectsProjectIdChunksGetRaw(requestParameters: ProjectsProjectIdChunksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Chunk>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdChunksGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/projects/{projectId}/chunks`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChunkFromJSON));
    }

    /**
     * Get details of all chunks in the project.
     */
    async projectsProjectIdChunksGet(requestParameters: ProjectsProjectIdChunksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Chunk>> {
        const response = await this.projectsProjectIdChunksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get project details.
     */
    async projectsProjectIdGetRaw(requestParameters: ProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/projects/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
    }

    /**
     * Get project details.
     */
    async projectsProjectIdGet(requestParameters: ProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project> {
        const response = await this.projectsProjectIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new project.
     */
    async projectsProjectIdPostRaw(requestParameters: ProjectsProjectIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/projects/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
    }

    /**
     * Create a new project.
     */
    async projectsProjectIdPost(requestParameters: ProjectsProjectIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project> {
        const response = await this.projectsProjectIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
